### ISSUE TITLE
feature request: add facility for token refreshment

### ISSUE THREAD

**Issue by gpolyn** [esplo/next-cognito#2]
A fairly well-documented issue for `amazon-cognito-auth-js` (see https://github.com/aws/amazon-cognito-auth-js/issues/92, for example) is the difficulty of token refreshment after the initial token's grant time of 1 hour or some other relatively impractical duration has elapsed.

Can this repo be enhanced to include facility for token refreshment?

(Thx for the repo!)

**Comment by esplo** [comment]
@gpolyn The answer to your question is "probably yes, but it can take a few days or weeks." These are the steps to add facility for token refreshment.

1. check current npm package of `aws/amazon-cognito-auth-js` whether we can use `auth.useCodeGrantFlow()`
2. upgrade `aws/amazon-cognito-auth-js` in package.json
3. comment out [this line](https://github.com/esplo/next-cognito/blob/master/hoc/ApplicationLayout.js#L59)
4. add a callback page and make an request to get an access token in this page
5. make a refresh mechanism (`auth.refreshSession(refreshtoken)`)

## additional explanation

- When I created this repository, [this merge request](https://github.com/aws/amazon-cognito-auth-js/pull/32) was  included in the `dist` folder, but not in npm package. It's because I have to check it first.

- A token by implicit grant flow will expire in an hour, and we cannot change it. We have to use authorize code grant flow instead of implicit grant flow to get a refresh token. Step 3 and step 4 are needed for this reason.

- Recently, I haven't used Cognito, Next, and even React! I need a time to catch up on them.

I'm sorry, but please wait for this implementation patiently.  Of course, PR is welcome!

**Comment by gpolyn** [comment]
Got it!
